# Generated by Django 5.2.5 on 2026-02-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_artwork_original_available_and_more'),
        ('store', '0002_alter_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'artwork')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item_type',
        ),
    ]
