# Generated by Django 5.2.5 on 2025-10-23 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('artist_statement', models.TextField(help_text="Artist's statement about this piece")),
                ('artwork_creation_date', models.DateField(help_text='When Jasem created this artwork')),
                ('original_height', models.DecimalField(decimal_places=2, help_text='Original height in cm', max_digits=8)),
                ('original_width', models.DecimalField(decimal_places=2, help_text='Original width in cm', max_digits=8)),
                ('original_depth', models.DecimalField(blank=True, decimal_places=2, help_text='Original depth in cm (for sculptures)', max_digits=8, null=True)),
                ('print_height', models.DecimalField(decimal_places=2, help_text='Print/photo height in cm', max_digits=8)),
                ('print_width', models.DecimalField(decimal_places=2, help_text='Print/photo width in cm', max_digits=8)),
                ('main_image', models.ImageField(upload_to='artworks/')),
                ('artwork_video', models.FileField(blank=True, help_text='Video of the artwork', null=True, upload_to='artworks/videos/')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_available', models.BooleanField(default=True)),
                ('second_option_price', models.DecimalField(decimal_places=2, help_text='Price for prints/photo sets', max_digits=10)),
                ('total_second_option_copies', models.PositiveIntegerField(default=50)),
                ('sold_second_option_copies', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SculptureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='sculptures/angles/')),
                ('angle_description', models.CharField(help_text="e.g., 'Front view', 'Side angle', 'Detail shot'", max_length=100)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order (1-8)')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sculpture_images', to='gallery.artwork')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('artwork', 'order')},
            },
        ),
    ]
