# Generated by Django 5.2.5 on 2026-02-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_category_options_category_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='original_available',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='original_depth',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='original_height',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='original_width',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='print_height',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='print_width',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='second_option_price',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='sold_second_option_copies',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='total_second_option_copies',
        ),
        migrations.AddField(
            model_name='artwork',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Depth in cm (for sculptures)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Height in cm', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is this item available for purchase?'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_limited_edition',
            field=models.BooleanField(default=False, help_text='Check if this is a limited edition (prints/photo sets)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='original_artwork',
            field=models.ForeignKey(blank=True, help_text='Link to the original artwork (for prints/photo sets only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to='gallery.artwork'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Price for this item', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='sold_copies',
            field=models.PositiveIntegerField(default=0, help_text='Number of copies sold'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='total_copies',
            field=models.PositiveIntegerField(default=0, help_text='Total number of copies available (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Width in cm', max_digits=8),
            preserve_default=False,
        ),
    ]
