# Generated by Django 5.2.5 on 2026-02-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_create_new_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculptureimage',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm (for printed images)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sculptureimage',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm (for printed images)', max_digits=6, null=True),
        ),
    ]
