# Generated by Django 5.2.5 on 2025-10-23 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('contact_type', models.CharField(choices=[('general', 'General Inquiry'), ('commission', 'Commission Request'), ('media', 'Media Inquiry'), ('exhibition', 'Exhibition Opportunity'), ('collaboration', 'Collaboration')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact_attachments/')),
                ('is_responded', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('page_type', models.CharField(choices=[('about', 'About Us'), ('artist_bio', 'Artist Biography'), ('contact', 'Contact Information'), ('shipping', 'Shipping Policy'), ('returns', 'Returns Policy'), ('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('faq', 'FAQ')], max_length=20, unique=True)),
                ('content', models.TextField()),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_menu', models.BooleanField(default=False)),
                ('menu_order', models.PositiveIntegerField(default=0)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
            ],
            options={
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Jasem Shuman Art', max_length=200)),
                ('site_tagline', models.CharField(blank=True, default='Contemporary Palestinian Artist', max_length=200)),
                ('contact_email', models.EmailField(default='info@jasemshuman.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('default_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar')], default='USD', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('enable_newsletter', models.BooleanField(default=True)),
                ('enable_wishlist', models.BooleanField(default=True)),
                ('enable_reviews', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('behance', 'Behance'), ('artsy', 'Artsy')], max_length=20, unique=True)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('update_type', models.CharField(choices=[('news', 'General News'), ('exhibition', 'Exhibition'), ('new_work', 'New Artwork'), ('achievement', 'Achievement'), ('media', 'Media Coverage')], default='news', max_length=20)),
                ('summary', models.TextField(help_text='Brief summary for listings', max_length=300)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('image_caption', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('related_artworks', models.ManyToManyField(blank=True, to='gallery.artwork')),
            ],
            options={
                'verbose_name': 'News Update',
                'verbose_name_plural': 'News Updates',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, help_text="Job title or description (e.g., 'Art Collector')", max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('testimonial', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('related_artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.artwork')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
