# Generated by Django 5.2.5 on 2025-10-29 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Select artwork to display in homepage hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.artwork'),
        ),
    ]
