# Generated by Django 5.2.5 on 2025-10-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitesettings_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='jasem_403@hotmail.com', max_length=254),
        ),
    ]
