# Generated by Django 5.2.5 on 2026-02-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_sitesettings_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='JASEM SHUMAN', max_length=200)),
                ('hero_subtitle', models.CharField(default='Artist', max_length=200)),
                ('hero_description', models.TextField(default='Contemporary Palestinian artist exploring the intersection of traditional techniques and modern expression.', help_text='Description text shown below hero image')),
                ('featured_section_title', models.CharField(default='Featured Artworks', max_length=100)),
                ('featured_section_subtitle', models.CharField(blank=True, max_length=200)),
                ('recent_section_title', models.CharField(default='Recent Works', max_length=100)),
                ('recent_section_subtitle', models.CharField(blank=True, max_length=200)),
                ('categories_section_title', models.CharField(default='Explore by Category', max_length=100)),
                ('categories_section_subtitle', models.CharField(blank=True, max_length=200)),
                ('show_featured_section', models.BooleanField(default=True)),
                ('show_recent_section', models.BooleanField(default=True)),
                ('show_categories_section', models.BooleanField(default=True)),
                ('featured_artworks_count', models.PositiveIntegerField(default=6, help_text='Number of featured artworks to display')),
                ('recent_artworks_count', models.PositiveIntegerField(default=8, help_text='Number of recent artworks to display')),
            ],
            options={
                'verbose_name': 'Gallery Page Settings',
                'verbose_name_plural': 'Gallery Page Settings',
            },
        ),
    ]
