# Generated by Django 5.2.5 on 2026-02-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_category_options_category_display_name_and_more'),
        ('pages', '0004_gallerypagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award_title', models.CharField(help_text='Name of the award', max_length=200)),
                ('organization', models.CharField(help_text='Organization that gave the award', max_length=200)),
                ('year', models.PositiveIntegerField(help_text='Year received')),
                ('description', models.TextField(blank=True, help_text='Details about the award')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='awards/')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Artist Award',
                'verbose_name_plural': 'Artist Awards',
                'ordering': ['-year', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ArtistEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree_title', models.CharField(help_text='e.g., Bachelor of Fine Arts', max_length=200)),
                ('institution', models.CharField(help_text='University or institution name', max_length=200)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=200)),
                ('year_start', models.PositiveIntegerField(help_text='Year started')),
                ('year_end', models.PositiveIntegerField(blank=True, help_text='Year completed (leave blank if ongoing)', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about this education')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order to display (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Artist Education',
                'verbose_name_plural': 'Artist Education',
                'ordering': ['-year_start', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ArtistPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Article or publication title', max_length=200)),
                ('publication_type', models.CharField(choices=[('article', 'Magazine/Newspaper Article'), ('interview', 'Interview'), ('review', 'Art Review'), ('catalog', 'Exhibition Catalog'), ('book', 'Book Feature'), ('online', 'Online Publication')], default='article', max_length=20)),
                ('publication_name', models.CharField(help_text='Magazine, newspaper, or website name', max_length=200)),
                ('author', models.CharField(blank=True, help_text='Author or journalist name', max_length=200)),
                ('publication_date', models.DateField(help_text='Date published')),
                ('description', models.TextField(blank=True, help_text='Brief description or excerpt')),
                ('url', models.URLField(blank=True, help_text='Link to online article')),
                ('pdf_file', models.FileField(blank=True, help_text='Upload PDF of the article', null=True, upload_to='publications/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publications/')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Publication/Press',
                'verbose_name_plural': 'Publications & Press',
                'ordering': ['-publication_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Exhibition or event name', max_length=200)),
                ('exhibition_type', models.CharField(choices=[('solo', 'Solo Exhibition'), ('group', 'Group Exhibition'), ('convention', 'Art Convention'), ('workshop', 'Workshop'), ('fair', 'Art Fair'), ('residency', 'Artist Residency'), ('other', 'Other Event')], default='group', max_length=20)),
                ('venue', models.CharField(help_text='Gallery, museum, or location name', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('start_date', models.DateField(help_text='Event start date')),
                ('end_date', models.DateField(blank=True, help_text='Event end date (leave blank for one-day events)', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the exhibition or event')),
                ('role', models.CharField(blank=True, help_text="Your role (e.g., 'Featured Artist', 'Workshop Instructor')", max_length=200)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='exhibitions/')),
                ('website_url', models.URLField(blank=True, help_text='Exhibition website or event page')),
                ('is_featured', models.BooleanField(default=False, help_text='Show prominently on gallery page')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('featured_artworks', models.ManyToManyField(blank=True, help_text='Artworks shown in this exhibition', to='gallery.artwork')),
            ],
            options={
                'verbose_name': 'Exhibition/Event',
                'verbose_name_plural': 'Exhibitions & Events',
                'ordering': ['-start_date', 'display_order'],
            },
        ),
    ]
